[project]
name = "gliger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "NoRaincheck", email = "2498638+NoRaincheck@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "gliclass>=0.1.20",
]

[tool.ruff]
line-length = 120

[dependency-groups]
dev = [
    "ruff>=0.16.8",
    "ty>=0.0.82",
]
